name: Deploy hostel-wordpress-theme

on:
  push:
    branches: [main]

jobs:
  deploy-to-first-host:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REGRU_HOST }}
          username: ${{ secrets.REGRU_USER }}
          key: ${{ secrets.REGRU_KEY }}
          script: |
            #cd /var/www/u1538455/data/www/hostelrzn.ru/wp-content/themes/hostelrzn
            #git clone git@github.com:site100ru/hostel-wordpress-theme.git .
            
            cd /var/www/u1538455/data/www/hostelrzn.ru/wp-content/themes/hostelrzn
            git pull
